version: '3'
services:
  server:
    build: ./back-end
    ports:
      - "5000:5000"
    volumes:
      - notes-db-data:/back-end
  web:
    build: ./front-end
    ports: 
      - "8080:8080"
volumes:
  notes-db-data:
